---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: chef_zero
  chef_version: <%= ENV['CHEF_VERSION'] || 12 %>

verifier:
  name: inspec

platforms:
# Ubuntu 12.04 LTS Precise Pangolin
- name: ubuntu-12.04
  driver:
    box: bento/ubuntu-12.04
# Ubuntu 14.04 LTS Trusty Tahr
- name: ubuntu-14.04
  driver:
    box: bento/ubuntu-14.04
# CentOS 6.8
- name: centos-6.8
  driver:
    box: bento/centos-6.8
# CentOS 7.2
- name: centos-7.2
  driver:
    box: bento/centos-7.2

  # Windows 2012
  - name: windows2012r2
    driver:
      box: mwrock/Windows2012R2

suites:
- name: default
  run_list:
  - recipe[newrelic-infra::default]
  attributes:
    newrelic_infra:
      features:
        host_integrations: true
      config:
        license_key: abcd
      host_integrations:
        config:
          cassandra:
            username: test
            password: kitchen
