driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 15 %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  chef_license: accept

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /sbin/init
- name: centos-8
  driver:
    image: dokken/centos-8
    pid_one_command: /sbin/init
- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
- name: ubuntu-20.04
  driver:
    image: dokken/ubuntu-20.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap-15.3
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN /usr/bin/zypper ref
